"""Build netem delay-distribution tables (``/usr/lib/tc/*.dist``) from samples.

netem draws jitter as ``delay + jitter * table[uniform] / NETEM_DIST_SCALE``:
the ``distribution`` argument names a table of signed 16-bit values that encode
the *shape* (the inverse CDF of the normalized distribution, scaled by 8192),
while ``delay``/``jitter`` supply location and scale. iproute2 ships only
``normal``, ``pareto`` and ``paretonormal``; a field-measured delay
distribution (e.g. the lognormal-tailed one-way delay of a cellular uplink,
which ``normal`` badly under-tails) becomes reproducible by generating its own
table from samples and installing it next to the builtin ones.

This is the same construction as iproute2's ``maketable``: sort the samples,
normalize to mean 0 / stddev 1, take :data:`TABLE_SIZE` inverse-CDF points,
scale by :data:`NETEM_DIST_SCALE` and clamp to int16.

Usage (module CLI)::

    python -m rosotacom.netem_dist samples.csv --column delay_ms --out field.dist

The output installs as ``/usr/lib/tc/field.dist`` and is then addressable as
``distribution: field`` (with ``distribution_file`` pointing at the file, so
profile runners install it into the shaping netns themselves).
"""

from __future__ import annotations

import argparse
import csv
import math
from collections.abc import Sequence
from pathlib import Path

NETEM_DIST_SCALE = 8192  # kernel: delay = mu + sigma * table[r] / 8192
TABLE_SIZE = 4096  # entries in the shipped iproute2 tables
_INT16_MIN, _INT16_MAX = -32768, 32767


def build_dist_table(samples: Sequence[float], *, table_size: int = TABLE_SIZE) -> list[int]:
    """Inverse-CDF table of the normalized ``samples`` (int16, netem scaling)."""
    values = sorted(float(x) for x in samples if math.isfinite(float(x)))
    if len(values) < 100:
        raise ValueError(f"need at least 100 finite samples for a stable table, got {len(values)}")
    mean = sum(values) / len(values)
    var = sum((x - mean) ** 2 for x in values) / len(values)
    sigma = math.sqrt(var)
    if sigma <= 0:
        raise ValueError("samples have zero spread; a distribution table is meaningless")
    table: list[int] = []
    n = len(values)
    for i in range(table_size):
        # midpoint quantile of bucket i, linearly interpolated in the sorted samples
        q = (i + 0.5) / table_size
        pos = q * (n - 1)
        lo = int(pos)
        frac = pos - lo
        x = values[lo] if lo + 1 >= n else values[lo] * (1 - frac) + values[lo + 1] * frac
        z = (x - mean) / sigma
        table.append(max(_INT16_MIN, min(_INT16_MAX, round(z * NETEM_DIST_SCALE))))
    return table


def format_dist_file(table: Sequence[int], *, comment: str | None = None) -> str:
    """Render a table in the ``/usr/lib/tc/*.dist`` text format (8 values/line)."""
    lines = [f"# {line}" for line in (comment or "").splitlines() if line]
    for i in range(0, len(table), 8):
        lines.append(" ".join(f"{v:d}" for v in table[i : i + 8]))
    return "\n".join(lines) + "\n"


def read_samples_csv(path: str | Path, column: str) -> list[float]:
    out: list[float] = []
    with open(path, newline="", encoding="utf-8") as fp:
        reader = csv.DictReader(fp)
        if reader.fieldnames is None or column not in reader.fieldnames:
            raise ValueError(f"{path}: no column {column!r}; columns: {reader.fieldnames}")
        for row in reader:
            text = (row.get(column) or "").strip()
            if text:
                try:
                    out.append(float(text))
                except ValueError:
                    continue
    return out


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("samples_csv", help="CSV with one numeric column of delay samples")
    parser.add_argument("--column", default="delay_ms", help="column to read (default: delay_ms)")
    parser.add_argument("--out", required=True, help="output .dist path (basename = table name)")
    parser.add_argument("--comment", default=None, help="provenance line(s) for the file header")
    args = parser.parse_args(argv)
    samples = read_samples_csv(args.samples_csv, args.column)
    table = build_dist_table(samples)
    comment = args.comment or (
        f"generated by rosotacom.netem_dist from {Path(args.samples_csv).name} ({len(samples)} samples)"
    )
    Path(args.out).write_text(format_dist_file(table, comment=comment), encoding="utf-8")
    print(f"wrote {args.out}: {len(table)} entries from {len(samples)} samples")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
