parameters:
  session_dir: /ws/example/5_sized_payload
  peer_dir: ${session_dir}/a

  ip_local: tks-seat_tks
  local_name: a
  ip_remote: tks-leitstand-02_tks
  remote_name: b

  qos_config_file: ${session_dir}/qos.yaml

  in: true
  topic_list_paths_inbound: ${session_dir}/b_to_a_topics.txt

  out: true
  topic_list_paths_outbound: ${session_dir}/a_to_b_topics.txt

  topic_monitor: true

  otaw: true
  otaw_config_file: ${peer_dir}/ota_wrapper.yaml
  otaw_suffix: /ota_stamped

  otau: true
  otau_config_file: ${peer_dir}/ota_unwrapper.yaml
  otau_suffix: /ota_stamped
